### ISSUE TITLE
Confusing usage of custom_headers

### ISSUE THREAD

**Issue by Comsapik** [smtp2go-oss/smtp2go-python#5]
**custom_headers** as described in README.md **are not email headers** but HTTP headers sent to the API.

I struggled a while trying to set a `Reply-To` header, which at last will not be part of the API payload...

https://github.com/smtp2go-oss/smtp2go-python/blob/929518203583c82db45e3c8bfb143df23b310a50/README.md?plain=1#L48
https://github.com/smtp2go-oss/smtp2go-python/blob/929518203583c82db45e3c8bfb143df23b310a50/smtp2go/core.py#L82-L83

Setting custom email headers is however described in the API docs : https://apidoc.smtp2go.com/documentation/#/POST%20/email/send

**Comment by david-smtp2go** [comment]
This is now fixed as of 2.3.0 and works as per the README.md
