### ISSUE TITLE
Default value of custom_headers should be an empty dict

### ISSUE THREAD

**Issue by Comsapik** [smtp2go-oss/smtp2go-python#6]
When no `custom_headers` passed, `client.send` crashes.

https://github.com/smtp2go-oss/smtp2go-python/blob/f8da38593d91880923db5ba22e6a640d3e4544c1/smtp2go/core.py#L59

**Comment by david-smtp2go** [comment]
Fixed in new release. Default value of custom_headers is now an empty dict.
